version: "3.8"

services:
  database:
    container_name: database
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gqlgen_todos
    ports:
      - 5432:5432
    volumes:
      - gqlgen_todos_data:/var/lib/postgresql/data 

volumes:
  gqlgen_todos_data: